name: Java CI with Maven and Allure Report Deployment

on:
  push:
    branches: [ Petstore_api ]
  pull_request:
    branches: [ Petstore_api ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 15
        uses: actions/setup-java@v3
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Build and test with Maven
        run: mvn clean test

      - name: Generate Allure Report
        run: mvn allure:generate

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/allure-report
      - name: Build and test with Maven
        run: mvn clean test allure:report