name: GitHub Action

on:
  push:
    branches: [ "Petstore_api" ]
  pull_request:
    branches: [ "Petstore_api" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Generate Allure report
        run: mvn allure:report

      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
                name: allure-report
                path: target/site/allure-maven

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on:
    publish_dir: ./target/site/allure-maven